---
title: "CuriosiDados"
---

## Introdução

<br />

Neste repositório deixarei os projetos de data science que for elaborando. Alguns estarão escritos em R (R markdown) e outros em Python (Jupyter Notebook). Deixarei abaixo dos projetos também, os links para o medium, com textos explicando mais a fundo os projetos _ uma espécie de storytelling.

> Os projetos em R estão acessíveis nos menus do topo.

## Projetos em Python

---

### IDEB 

- Análise dos dados do IDEB nacional, para entender o desempenho do ensino fundamental e médio no Brasil (escolas públicas e privadas);
- <a href="https://github.com/heavyrick/datascience/blob/master/analises/ideb/ideb_nacional.ipynb" target="_blank">IDEB (Link do notebook)</a>
- Textos no **Medium**: <a href="https://medium.com/@heavyrick/ad-ideb-introdu%C3%A7%C3%A3o-8c3eab6fb6d8" target="_blank">Ideb — introdução</a> e <a href="https://medium.com/@heavyrick/ad-ideb-nacional-2d07ee2863dd" target="_blank">Ideb nacional</a>

---

### Salário Mínimo e Necessário

- Análise de dados do salário mínimo e do salário mínimo necessário, com dados do Dieese;
- <a href="https://github.com/heavyrick/datascience/blob/master/analises/salario_minimo_dieese/salario_minimo.ipynb" target="_blank">Salário Mínimo x Salário Mínimo Necessário (Link do notebook)</a>
- Texto no **Medium**: <a href="https://medium.com/@heavyrick/ad-sal%C3%A1rio-m%C3%ADnimo-e-necess%C3%A1rio-4f8bde6d1252" target="_blank">Salário Mínimo e Necessário</a>

---

### Preço do Gás de Cozinha

- Análise de dados do preço de revenda do gás de cozinha, com dados da ANP (Agência Nacional de Petróleo);
- <a href="https://github.com/heavyrick/datascience/blob/master/analises/preco_gas_cozinha/precos_gas_cozinha.ipynb" target="_blank">Preço do Gás de Cozinha (Link do notebook)</a>
- Texto no **Medium**: <a href="https://medium.com/@heavyrick/pre%C3%A7o-do-g%C3%A1s-de-cozinha-400237cabd52" target="_blank">Preço do Gás de Cozinha</a>

---

### Pink Floyd Wordcloud

- Wordcloud com as palavras mais usadas em suas letras pela banda inglesa Pink Floyd
- <a href="https://github.com/heavyrick/datascience/blob/master/analises/pink_floyd_wordcloud/pink_floyd_wordcloud.ipynb" target="_blank">Pink Floyd Wordcloud (Link do notebook)</a>

---

## Sobre mim

Entrei muito por acaso no antigo curso de Processamento de Dados da Fatec de Americana/SP, com praticamente nenhum conhecimento da área _ sabia baixar músicas no emule e no ares, crackear jogo e editar código CSS dentro do Orkut, no máximo. E lá dentro aprendi mais o que eu não queria fazer, do que eu queria fazer. E mexer no Delphi e criar páginas em HTML foram as coisas mais legais do curso todo. 

Daí em diante, programar para a web foi o que eu mais queria fazer enquanto profissão. Ao começar a programar em PHP, um outro gosto foi surgindo, que era trabalhar com dados, desde planilhas de excel, passando pelo MySQL e até chegar no Oracle. Mas o processo todo me animava: desde a coleta, tratamento, organização e finalmente sua apresentação e posterior análise.

Claro que o tempo não é algo infinito, e não havia tempo para me dedicar apenas a questão dos dados, tinha que continuar evoluindo nas outras tecnologias ligadas à programação: css, bootstrap, javascript, jquery, angular (1,2,4 .. 7), node, wordpress, laravel, zend, python. Mas um belo dia surge essa tal área de Ciência de Dados, que dá a oportunidade do uso das habilidades também de programação, para a criação de análises muito interessantes dessas massas de dados cada vez maiores criadas nesses tempos digitais, de inúmeras áreas possíveis, e áreas ainda nem pensadas ou exploradas.

Esse espaço é destinado aos resultados da teoria e práticas que tenho me dedicado na área de análise de dados.

#### Contatos
- <a href="https://www.linkedin.com/in/ricardofilho6/" target="_blank">LinkedIn</a>
- <a href="https://medium.com/@heavyrick" target="_blank">Medium</a>
- <a href="https://github.com/heavyrick/datascience" target="_blank">Github</a>

