---
title: "Last FM"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r lfm-01, warning=FALSE}

#100 Artistas mais ouvidos (mais scrobblers)
#Músicas mais ouvidos de uma lista de artistas (Queen, Lana del Rey, Iron Maiden, Lady Gaga, Caetano Veloso)
#Checar se existe um arquivo CSV, se não, consultar a API, buscar os dados e preencher o dataframe o/

#Bibliotecas
library(highcharter)
library(dplyr)
library(httr)
library(jsonlite)
library(stringr)

```

```{r lfm-02, include=FALSE}

#################################################################################################
# API LAST FM
#################################################################################################

# Buscar as músicas mais tocadas de um artista

# artist.getTopTracks
# https://www.last.fm/api/show/artist.getTopTracks
# JSON: /2.0/?method=artist.gettoptracks&artist=cher&api_key=YOUR_API_KEY&format=json

# Params
# artist (Required (unless mbid)] : The artist name
# mbid (Optional) : The musicbrainz id for the artist
# autocorrect[0|1] (Optional) : Transform misspelled artist names into correct artist names, returning the correct version instead. The corrected artist name will be returned in the response.
# page (Optional) : The page number to fetch. Defaults to first page.
# limit (Optional) : The number of results to fetch per page. Defaults to 50.
# api_key (Required) : A Last.fm API key.

#################################################################################################

# Buscar artistas mais tocados

# chart.getTopArtists
# https://www.last.fm/api/show/chart.getTopArtists
# JSON: /2.0/?method=chart.gettopartists&api_key=YOUR_API_KEY&format=json

# Params
# page (Optional) : The page number to fetch. Defaults to first page.
# limit (Optional) : The number of results to fetch per page. Defaults to 50.
# api_key (Required) : A Last.fm API key.

#################################################################################################

# Configuração da conexão com a API

API_URL_ROOT <- 'http://ws.audioscrobbler.com/2.0/?'
API_KEY <- '5248ea3d041e324f539eb0b2852c5532'

```




```{r lfm-03, include=FALSE}

info = file.info(c('data/lastfm_topartists.csv', 'data/arquivo_vazio.csv', 'data/arquivo.csv'))
info



connectApi <- function(api_method, artista = NULL, tags = NULL){
  # Conectar na api e receber os dados
  params <- list(api_key = API_KEY, format = "json", method = api_method, limit='100')
  
  if(!is.null(artista)){
    params <- c(list(artist = artista), params)
  }
  
  if(!is.null(tags)){
    params <- c(list(tag = tags), params)
  }
    
  #print(params)
  
  endpoint_response <- GET(API_URL_ROOT, query = params) # conectar na API
  if(status_code(endpoint_response) != 200){ # validar resposta
    return(FALSE)
  }
  
  print(content(endpoint_response, as="text", encoding = 'UTF-8'))

  # Retornar dados e convertê-los em json e atribuir a um dataframe
  body_json <- fromJSON(content(endpoint_response, as="text", encoding = 'UTF-8'), flatten = TRUE)
  #body_df <- as.data.frame(body_json)

  return(body_json)
}


```

```{r lfm-03}

#df_topartists <- connectApi('chart.gettopartists')
#df_toptrackartists <- connectApi('chart.gettoptracks')
df_toptags <- connectApi('tag.gettopartists',  tags = 'heavy+metal')


#df_topartistas[, c(0:5)]

# 
#write.csv(df_topartistas[, c(0:5)], file='data/lastfm_topartists.csv',  fileEncoding = 'UTF-8')

#write.table(df_topartistas[, c(0:5)], file='data/lastfm_topartists.csv', sep = ",", col.names = !file.exists("data/lastfm_topartists.csv"), append = T, fileEncoding = 'UTF-8')

```

```{r}

#df_topartistas[1, 'artists..attr.totalPages']


# for(i in c('A', 'B', 'C', 'D', 'E', 'F', 'G')){
#    Sys.sleep(1)
#    print(i)
# }



```



<br />

# Introdução

Neste projeto vamos 




